# Generated by Django 5.2.4 on 2025-07-13 11:08

import app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_company_id, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_university_id, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='InternshipPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_position_id, editable=False, max_length=12, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('skills_required', models.TextField()),
                ('duration', models.CharField(choices=[('2', '2 Months'), ('3', '3 Months'), ('4', '4 Months'), ('6', '6 Months')], default='2', max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, help_text='Stipend amount in PKR', max_digits=10, null=True)),
                ('max_students', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_application_id, editable=False, max_length=14, unique=True)),
                ('cover_letter', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.internshipposition')),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_nanoid, editable=False, max_length=12, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('specialization', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_nanoid, editable=False, max_length=12, unique=True)),
                ('scheduled_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.internshipapplication')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mentorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='internshipposition',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mentorprofile'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_nanoid, editable=False, max_length=12, unique=True)),
                ('notification_type', models.CharField(choices=[('application_status', 'Application Status Update'), ('interview_scheduled', 'Interview Scheduled'), ('progress_reminder', 'Progress Report Reminder'), ('internship_completed', 'Internship Completed'), ('general', 'General Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_nanoid, editable=False, max_length=12, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_nanoid, editable=False, max_length=12, unique=True)),
                ('payment_type', models.CharField(choices=[('student_fee', 'Student Registration Fee'), ('mentor_fee', 'Mentor/Company Fee')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in PKR', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_nanoid, editable=False, max_length=12, unique=True)),
                ('student_id', models.CharField(max_length=50)),
                ('year_of_study', models.CharField(choices=[('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
                ('major', models.CharField(max_length=100)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('skills', models.TextField(help_text='List your technical and soft skills')),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('portfolio_url', models.URLField(blank=True)),
                ('expected_graduation', models.DateField()),
                ('is_available_for_internship', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.university')),
            ],
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentprofile'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_nanoid, editable=False, max_length=12, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.university')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_nanoid, editable=False, max_length=12, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('on_hold', 'On Hold')], default='active', max_length=15)),
                ('final_grade', models.CharField(blank=True, max_length=2)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.internshipapplication')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mentorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.CharField(db_index=True, default=app.models.generate_nanoid, editable=False, max_length=12, unique=True)),
                ('report_type', models.CharField(choices=[('student', 'Student Report'), ('mentor', 'Mentor Report'), ('teacher', 'Teacher Report')], max_length=10)),
                ('week_number', models.IntegerField()),
                ('tasks_completed', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('challenges_faced', models.TextField(blank=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('student_performance', models.TextField(blank=True)),
                ('skills_demonstrated', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('attendance_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('discussion_notes', models.TextField(blank=True)),
                ('academic_alignment', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='app.internship')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('internship', 'report_type', 'week_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together={('student', 'position')},
        ),
    ]
