# Generated by Django 5.2.4 on 2025-07-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_company_address_alter_company_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='final_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='reviewer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='academic_alignment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='areas_for_improvement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='challenges_faced',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='discussion_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='skills_demonstrated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='student_performance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='tasks_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
