# Generated by Django 5.2.4 on 2025-07-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_studentprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain_verified',
            field=models.BooleanField(default=False, help_text='Whether the email domain has been verified'),
        ),
        migrations.AddField(
            model_name='company',
            name='email_domain',
            field=models.CharField(blank=True, help_text='Official email domain (e.g., company.com)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='domain_verified',
            field=models.BooleanField(default=False, help_text='Whether the email domain has been verified'),
        ),
        migrations.AddField(
            model_name='institute',
            name='email_domain',
            field=models.CharField(blank=True, help_text='Official email domain (e.g., university.edu.pk)', max_length=100, null=True),
        ),
    ]
