# Generated by Django 5.2.4 on 2025-08-28 21:09

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_internship_application_alter_internship_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='internship',
            name='eligible_semesters',
            field=models.CharField(default='4-8', max_length=32),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='officialprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('nanoid', models.CharField(default=app.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], max_length=16)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('nanoid', models.CharField(default=app.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('task_description', models.TextField()),
                ('performance_notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipReport',
            fields=[
                ('nanoid', models.CharField(default=app.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('report_file', models.FileField(upload_to='internship_reports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_reports', to='app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OnCampusSupervisorEvaluation',
            fields=[
                ('nanoid', models.CharField(default=app.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('evaluation_file', models.FileField(upload_to='oncampus_evaluations/')),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncampus_evaluations', to='app.studentprofile')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OnSiteSupervisorEvaluation',
            fields=[
                ('nanoid', models.CharField(default=app.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('evaluation_file', models.FileField(upload_to='onsite_evaluations/')),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onsite_evaluations', to='app.studentprofile')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app.mentorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyActivityLog',
            fields=[
                ('nanoid', models.CharField(default=app.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('log_file', models.FileField(upload_to='activity_logs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='app.studentprofile')),
            ],
        ),
    ]
