# Generated by Django 5.2.5 on 2025-08-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_internship_application_alter_internship_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='degree_programs',
            field=models.BooleanField(default=False, help_text='Offers degree-level programs'),
        ),
        migrations.AddField(
            model_name='institute',
            name='district',
            field=models.CharField(blank=True, choices=[('Abbottabad', 'Abbottabad'), ('Bajaur', 'Bajaur'), ('Bannu', 'Bannu'), ('Battagram', 'Battagram'), ('Bunner', 'Bunner'), ('Charsadda', 'Charsadda'), ('D.I.Khan', 'D.I.Khan'), ('Dir Lower', 'Dir Lower'), ('Dir Upper', 'Dir Upper'), ('Hangu', 'Hangu'), ('Haripur', 'Haripur'), ('Karak', 'Karak'), ('Khyber', 'Khyber'), ('Kohat', 'Kohat'), ('Kohistan', 'Kohistan'), ('Kurram', 'Kurram'), ('Lakki Marwat', 'Lakki Marwat'), ('Lower Chitral', 'Lower Chitral'), ('Malakand', 'Malakand'), ('Mansehra', 'Mansehra'), ('Mardan', 'Mardan'), ('Mohmand', 'Mohmand'), ('North Waziristan', 'North Waziristan'), ('Nowshera', 'Nowshera'), ('Orakzai', 'Orakzai'), ('Peshawar', 'Peshawar'), ('Shangla', 'Shangla'), ('South Waziristan', 'South Waziristan'), ('Swabi', 'Swabi'), ('Swat', 'Swat'), ('Tank', 'Tank'), ('Upper Chitral', 'Upper Chitral')], help_text='District where the institute is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='female_students_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of female students enrolled'),
        ),
        migrations.AddField(
            model_name='institute',
            name='male_students_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of male students enrolled'),
        ),
        migrations.AddField(
            model_name='institute',
            name='management_programs',
            field=models.BooleanField(default=False, help_text='Offers management programs'),
        ),
        migrations.AddField(
            model_name='institute',
            name='postgraduate_programs',
            field=models.BooleanField(default=False, help_text='Offers postgraduate programs'),
        ),
        migrations.AddField(
            model_name='institute',
            name='primary_education_level',
            field=models.CharField(blank=True, choices=[('Degree', 'Degree'), ('PostGraduate', 'Post Graduate'), ('Management', 'Management')], help_text='Primary level of education offered', max_length=20, null=True),
        ),
    ]
