# Generated by Django 5.2.4 on 2025-09-07 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_internship_duration_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.internship'),
        ),
    ]
