# Generated by Django 5.2.5 on 2025-08-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_institute_demographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='officialprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
    ]
