# Generated by Django 5.2.5 on 2025-08-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_phone_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester_of_study',
            field=models.CharField(blank=True, choices=[('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'), ('7', '7th Semester'), ('8', '8th Semester')], max_length=1, null=True),
        ),
    ]
