# Generated by Django 5.2.5 on 2025-08-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_year_to_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='internshipapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'under_review', 'interview_scheduled', 'approved'])), fields=('student', 'position'), name='unique_active_application'),
        ),
    ]
