# Generated by Django 5.2.5 on 2025-08-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_allow_reapplication_after_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
    ]
